# Generated by Django 2.2.15 on 2020-08-25 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200825_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.Catalogue'),
        ),
    ]
