# Generated by Django 2.2.15 on 2020-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(to='market.Product'),
        ),
    ]
