# Generated by Django 2.2.15 on 2020-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20200825_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='products',
            field=models.ManyToManyField(related_name='articles', to='market.Product'),
        ),
    ]
