# Generated by Django 2.2.15 on 2020-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200825_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.CharField(default='nopic.jpg', max_length=100),
        ),
    ]
