# Generated by Django 2.2.15 on 2020-08-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20200831_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brief',
            field=models.CharField(default='Краткое описание статьи', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='pics/nopic.jpg', upload_to='pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=6000),
        ),
    ]
