# Generated by Django 2.2.15 on 2020-08-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20200831_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=15000),
        ),
    ]
