# Generated by Django 2.2.15 on 2020-08-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20200831_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brief',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
