# Generated by Django 2.2.15 on 2020-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.CharField(max_length=250),
        ),
    ]
