# Generated by Django 2.2.15 on 2020-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20200902_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pretty_cart',
            field=models.CharField(default='no data yet', max_length=1000),
        ),
    ]
