# Generated by Django 2.2.15 on 2020-09-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_order_pretty_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
