# Generated by Django 2.2.15 on 2020-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20200902_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
